src/WebUI/Controllers/VocationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zenbot.Domain.Shared.Interfaces;
using Zenbot.WebUI.Extensions;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]
    public class VocationsController : Controller
    {
        private readonly IBotUserGuildService _botUserGuildService;
        private readonly IVocationServices _vocationServices;

        public VocationsController(IBotUserGuildService botUserGuildService, IVocationServices vocationServices)
        {
            _botUserGuildService = botUserGuildService;
            _vocationServices = vocationServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userid = HttpContext.GetOperatorUserId();

            var guilds = await _botUserGuildService.GetAllGuildsByUserId((ulong)userid);
            return View(guilds);
        }


        public async Task<IActionResult> VocationList(int guildId, string guildName)
        {
            ViewBag.guildName = guildName;
            var vocations = await _vocationServices.GetVocationListByGuildId(guildId);
            return View(vocations);
        }
    }
}

src/WebUI/Views/Vocations/Index.cshtml
@using Zenbot.Domain.Shared.Entities.Bot
@model IEnumerable<BotUserGuild>

@{
    ViewData["Title"] = "Vocation";
    Layout = "_PanelLayout";
    var counter = 1;
}

<div class="row g-3 my-2 bg-white pb-3">
    <div class="d-flex justify-content-between px-3">
        <div class="col-md-3">
        </div>

        <div class="col-md-3">
            <a href="#" class="text-dark">
                <div class=" custom-lightGray-bg shadow-sm d-flex justify-content-around align-items-center rounded py-2">
                    <div class="d-flex justify-content-around align-items-center">
                        <p class="fs-5 mb-0">Vocation Settings</p>
                        <i class="fas fa-birthday-cake fs-5 p-2"></i>
                    </div>
                </div>
            </a>

        </div>
    </div>

    <div class="p-4">
        <h5>All Servers</h5>
        <div class="p-4 border border-1 rounded-2">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Server Name</th>
                        <th scope="col">Join Date</th>
                        <th scope="col">Vocation Settings</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">
                            <th scope="row">@counter</th>
                            <td>@item.Guild.GuildName</td>
                            <td>@item.Guild.JoinDate.ToString("MMM dd yyyy")</td>
                            <td><a asp-action="VocationList" asp-controller="Vocations" asp-route-guildId="@item.GuildId"asp-route-guildName="@item.Guild.GuildName"><i class="fas fa-cogs me-2"></i></a></td>
                        </tr>
                        counter++;
                    }
                </tbody>
            </table>
        </div>

    </div>

</div>


  

src/WebUI/Views/Vocations/VocationList.cshtml
@using Zenbot.Domain.Shared.Entities.Bot
@model IEnumerable<Vocation>

@{
    ViewData["Title"] = "Vocation";
    Layout = "_PanelLayout";
    var counter = 1;
}

<div class="row g-3 my-2 bg-white pb-3">
    <div class="d-flex justify-content-between px-3">
        <div class="col-md-3">
        </div>

        <div class="col-md-3">
            <a href="#" class="text-dark">
                <div class=" custom-lightGray-bg shadow-sm d-flex justify-content-around align-items-center rounded py-2">
                    <div class="d-flex justify-content-around align-items-center">
                        <p class="fs-5 mb-0">Vocation Settings</p>
                        <i class="fas fa-birthday-cake fs-5 p-2"></i>
                    </div>
                </div>
            </a>

        </div>
    </div>

    <div class="p-4">
        <h5>All Vocations for <i>@ViewBag.guildName Server</i></h5>
        <div class="p-4 border border-1 rounded-2">
            <div class="row">
                @foreach (var item in Model)
                {
                    var days = Convert.ToInt32((item.EndDate - item.StartDate).TotalDays);
                    <div class="col-md-3 p-1">
                        <div class="border h-100 overflow-auto border-1 shadow hover-fade rounded p-3 "role="button">
                            <p class="text-center my-3"> <span style="background-color:@(item.IsAccept? "#40B22C": "#FF5733")" class="font-custom-size p-1 rounded">@(item.IsAccept? "Approved": "Rejected") </span> </p>
                        <p class="mb-1 font-custom-size"><strong>Applicatn: </strong> @item.UserRequest.Username</p>
                        <p class="mb-1 font-custom-size"><strong>Request Date: </strong> @item.RequestDate.ToString("dd/MM/yyyy")</p>
                        <p class="mb-1 font-custom-size"><strong>For: </strong> @days @(days>1? "Days": "Day") </p>
                        <p class="mb-1 font-custom-size"><strong>Request Days: </strong> From <br> @item.StartDate.ToString("dd/MM/yyyy") To @item.EndDate.ToString("dd/MM/yyyy")</p>
                        <p class="mb-1 font-custom-size"><strong>Supervisor: </strong> @item.Supervisor.Username</p>
                        <p class="mb-4 font-custom-size"><strong>Description: </strong> @item.Description</p>
                    </div></div>
                }

            </div>
        </div>

    </div>

</div>