src/WebUI/Controllers/BirthdayController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zenbot.Domain.Shared.Entities.Bot;
using Zenbot.Domain.Shared.Entities.Bot.Dtos;
using Zenbot.Domain.Shared.Interfaces;
using Zenbot.WebUI.Extensions;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]
    public class BirthdayController : Controller
    {
        private readonly IBotUserGuildService _botUserGuildService;
        private readonly IBirthdayMessageService _birthdayMessageService;
        private readonly INotyfService _notyf;
        public BirthdayController(IBotUserGuildService botUserGuildService, IBirthdayMessageService birthdayMessageService,INotyfService notyf)
        {
            _botUserGuildService = botUserGuildService;
            _birthdayMessageService = birthdayMessageService;
            _notyf = notyf;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userid = HttpContext.GetOperatorUserId();

            var guilds = await _botUserGuildService.GetAllGuildsByUserId((ulong)userid);
            return View(guilds);
        }

     
        public async Task<IActionResult> Edit(int guildId, string guildName)
        {
            var message = await _birthdayMessageService.GetBirthdayMessagesByGuildId(guildId);

            ViewBag.guildId = guildId;
            ViewBag.guildName = guildName;

            if (message != null)
            {
                var messageDto = new BirthdayMessageDto
                {
                    Message = message.Message,
                    IsActive = message.IsActive,
                    GuildId = message.GuildId,
                    Id = message.Id
                };
                return View(messageDto);
            }
            ViewBag.info = "The placeholder is the default Message for Birthday, but you can always customize it.";
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BirthdayMessageDto dto)
        {
            var bMessage = await _birthdayMessageService.UpdateBirthdayMessage(dto);
            if (bMessage) {
                _notyf.Success("Birthday message updated successfully");
                return RedirectToAction(nameof(Index));
            }
            else { _notyf.Error("Error occured during updating Birthday message"); return View(dto); }
        }
    }
}

src/WebUI/Controllers/BoardingController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Zenbot.Domain.Shared.Common;
using Zenbot.Domain.Shared.Entities.Bot;
using Zenbot.Domain.Shared.Entities.Bot.Dtos;
using Zenbot.Domain.Shared.Interfaces;
using Zenbot.WebUI.Extensions;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]

    public class BoardingController : Controller
    {
        private readonly IBotUserGuildService _botUserGuildService;
        private readonly IBoardingMessage _boardingMessageService;
        private readonly IBoardingFiles _boardingFiles;
        private readonly INotyfService _notyf;

        public BoardingController(IBotUserGuildService botUserGuildService, IBoardingMessage boardingMessageService, IBoardingFiles boardingFiles, INotyfService notyf)
        {
            _botUserGuildService = botUserGuildService;
            _boardingMessageService = boardingMessageService;
            _boardingFiles = boardingFiles;
            _notyf = notyf;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userid = HttpContext.GetOperatorUserId();

            var guilds = await _botUserGuildService.GetAllGuildsByUserId((ulong)userid);
            return View(guilds);
        }


        public async Task<IActionResult> Edit(int guildId, string guildName)
        {
            var message = await _boardingMessageService.GetBoardingMessagesByGuildId(guildId);

            ViewBag.guildId = guildId;
            ViewBag.guildName = guildName;


            if (message != null)
            {
                ICollection<BoardingFiles> messageFile = await _boardingFiles.GetBoardingFilesByBoardingMessageId(message.Id);
                ViewBag.messageFiles = messageFile;
                var messageDto = new BoardingMessageDto
                {
                    Message = message.Message,
                    IsActive = message.IsActive,
                    GuildId = message.GuildId,
                    Id = message.Id
                };
                ViewBag.messageId = messageDto.Id;
                return View(messageDto);
            }
            ViewBag.info = "The placeholder is the default Message for Birthday, but you can always customize it.";
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BoardingMessageDto dto)
        {
            var bMessage = await _boardingMessageService.UpdateBoardingMessage(dto);
            if (bMessage)
            {
                _notyf.Success("Boarding message updated successfully");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                _notyf.Error("Error occured during updating Boarding message"); return View(dto);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AttachFiles(List<IFormFile> files, int messageId, int guildId, string guildName)
        {
            await _boardingFiles.UpdateBoardingFiles(files, messageId, guildId);
            return RedirectToAction("Edit", new { guildId = guildId, guildName = guildName });
        }
    }
}

src/WebUI/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        // GET: /Panel/Index
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/WebUI/Controllers/ServerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zenbot.Domain.Shared.Interfaces;
using Zenbot.WebUI.Extensions;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]
    public class ServerController : Controller
    {
       
        private readonly IBotUserGuildService _botUserGuildService;
        private readonly IGuildService _guildService;
        private readonly INotyfService _notyf;
        public ServerController(IBotUserGuildService botUserGuildService, IGuildService guildService, INotyfService notyf)
        {
            _botUserGuildService = botUserGuildService;
            _guildService = guildService;
            _notyf = notyf;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userid = HttpContext.GetOperatorUserId();
            
            var guilds = await _botUserGuildService.GetAllGuildsByUserId((ulong)userid);
            return View(guilds);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AuthenticateGuild(int guildId, string password)
        {
            var result =await _guildService.UpdatePasswordForGuild(guildId, password);
            if (result)
            {
                _notyf.Success("Password for guild updated successfully");
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
            _notyf.Error("Error occured during updating password");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GSuiteAuth(int guildId, IFormFile gsuite)
        {
            var result = await _guildService.UpdateGSuiteAuthForGuild(guildId, gsuite);
            if (result)
            {
                _notyf.Success("G suite credentials updated successfully");
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Error occured during saving G suite file");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ScrinIOToken(int guildId, string scrinio)
        {
            var result = await _guildService.UpdateScrinIOForGuild(guildId, scrinio);
            if (result)
            {
                _notyf.Success("Scrin_io token updated successfully");
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Error occured during updating guild");
            return RedirectToAction(nameof(Index));
        }
    }
}

src/WebUI/Views/Shared/_AuthLayout.cshtml
@{
    Layout = "_BaseLayout";
}

@section Styles{
    <link rel="stylesheet" href="~/bundle/css/base-auth.min.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
}

@section Scripts{
    <script src="~/bundle/js/base-auth.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
}

<section class="auth-wrapper">
    <div class="auth-items">
        <div class="auth-banner">
            <div class="title">
                <span>Welcome to</span>
                <span>Zenbot</span>
            </div>
        </div>

        <section class="auth-form">
            @RenderBody()
        </section>
    </div>
</section>

src/WebUI/Views/Shared/_BaseLayout.cshtml
@{
    var pageTitle = $"{ViewData["Title"]} - Zenbot";
}

<!DOCTYPE html>

<html>

<head>
    <title>@pageTitle</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Zenbot">
    <meta name="keywords" content="Zenbot, Zencode, Bot, Discord">
    <link rel="icon" href="~/img/favicon.ico">
    <link rel="stylesheet" href="~/bundle/css/font.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bundle/css/base.min.css" asp-append-version="true" />
   
    @RenderSection("Styles", required: false)
</head>

<body>
    <h1 class="d-none">@pageTitle</h1>

    <main class="main-wrapper">
        @RenderBody()
    </main>

    <script src="~/bundle/js/base.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

src/WebUI/Views/Shared/_ErrorLayout.cshtml
@{
    Layout = "_BaseLayout";
}

@section Styles{
    <link rel="stylesheet" href="~/bundle/css/base-error.min.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
}

@section Scripts{
    <script src="~/bundle/js/base-error.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
}

<section class="container-fluid p-4 bg-dark d-flex flex-column flex-grow-1 justify-content-center">
    <div class="row justify-content-center">
        <section class="col-sm-12 col-md-8 col-lg-6 col-xl-4 py-3 bg-light rounded border shadow-lg text-center">
            @RenderBody()
        </section>
    </div>

    <div class="row mt-4">
        <div class="col-12 text-center">
            <a class="text-light hover-fade" asp-controller="@nameof(HomeController).GetControllerRoute()" asp-action="@nameof(HomeController.Index)">
                <span class="material-icons me-1 align-middle">arrow_back</span>
                <span class="align-middle">Go Back To Home</span>
            </a>
        </div>
    </div>
</section>

src/WebUI/Views/Shared/_HomeLayout.cshtml
@{
    Layout = "_BaseLayout";
}

@section Styles{
    <link rel="stylesheet" href="~/bundle/css/base-home.min.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
}

    @section Scripts{
    <script src="~/bundle/js/base-home.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
}

<header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="@nameof(HomeController).GetControllerRoute()" asp-action="@nameof(HomeController.Index)">
                <img src="~/img/logo-white.png" alt="Logo" />
                <span>zenbot</span>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#homeNavbar" aria-controls="homeNavbar" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="homeNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="@nameof(HomeController).GetControllerRoute()" asp-action="@nameof(HomeController.Index)">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="@nameof(ErrorController).GetControllerRoute()" asp-action="@nameof(ErrorController.Code403)">Tutorials</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="@nameof(ErrorController).GetControllerRoute()" asp-action="@nameof(ErrorController.Code403)">Support</a>
                    </li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="@nameof(PanelController).GetControllerRoute()" asp-action="@nameof(PanelController.Index)">Panel</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="@nameof(AccountController).GetControllerRoute()" asp-action="@nameof(AccountController.DiscordLogout)">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="@nameof(AccountController).GetControllerRoute()" asp-action="@nameof(AccountController.DiscordLogin)">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

<section class="container flex-grow-1 py-5">
    @RenderBody()
</section>

src/WebUI/Views/Shared/_PanelLayout.cshtml
@{
    Layout = "_BaseLayout";
}

@section Styles{
    <link rel="stylesheet" href="~/bundle/css/base-panel.min.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="styles.css" />
    @RenderSection("Styles", required: false)
}

    @section Scripts{
    <script src="~/bundle/js/base-panel.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function() {
            el.classList.toggle("toggled");
        };
    </script>


    @RenderSection("Scripts", required: false)
}


    <div>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar -->
            <div class="navbar-dark bg-dark" id="sidebar-wrapper">
                <div class="sidebar-heading text-center py-4 text-white fs-4 fw-bold text-uppercase border-bottom">
                    <img src="~/img/logo-colored.png" width="35" />Zenbot
                </div>
                <div class="list-group list-group-flush my-3 text-light">
                    <ul class="list-unstyled nav">

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Panel" class="nav-link text-white mx-3 @(ViewData["Title"].ToString() == "Panel" ? "active" : "") rounded-2">
                                <i class="fas fa-tachometer-alt me-2"></i>Dashboard
                            </a>
                        </li>

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Server" class="nav-link text-white mx-3 @(ViewData["Title"].ToString() == "Server" ? "active" : "") rounded-2">
                                <i class="fas fa-server me-2"></i>Servers
                            </a>
                        </li>


                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Birthday" class="nav-link text-white @(ViewData["Title"].ToString() == "Birthday" ? "active" : "") mx-3  rounded-2">
                                <i class="fas fa-birthday-cake me-2"></i> Birthday
                            </a>
                        </li>

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="JoinServer" class="nav-link text-white @(ViewData["Title"].ToString() == "Welcome" ? "active" : "") mx-3  rounded-2">
                                <i class="fas fa-hat-wizard me-2"></i>Join Server
                            </a>
                        </li>

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Boarding" class="nav-link text-white @(ViewData["Title"].ToString() == "Boarding" ? "active" : "") mx-3  rounded-2">
                                <i class="fas fa-tasks me-2"></i> Boarding
                            </a>
                        </li>

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Vocations" class="nav-link text-white @(ViewData["Title"].ToString() == "Vocation" ? "active" : "") mx-3 rounded-2">
                                <i class="fas fa-street-view me-2"></i>Vocation
                            </a>
                        </li>

                        <li class=" w-100 mb-2">
                            <a asp-action="Index" asp-controller="Integration" class="nav-link text-white @(ViewData["Title"].ToString() == "Integration" ? "active" : "") mx-3 rounded-2">
                                <i class="fas fa-solid fa-people-arrows me-2"></i>Integration
                            </a>
                        </li>

                    </ul>


                </div>
            </div>
            <!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            <div id="page-content-wrapper">
                <nav class="navbar navbar-expand-lg custom-lightGray-bg py-4 px-4">
                    <div class="d-flex align-items-center">
                        <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                        <h2 class="fs-2 m-0">Dashboard</h2>
                    </div>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark fw-bold" href="#" id="navbarDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-user me-2 text-dark"></i>@Context.GetOperatorUsername()
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">Profile</a></li>
                                    <li><a class="dropdown-item" href="#">Settings</a></li>
                                    <li><a class="dropdown-item" asp-action="DiscordLogout" asp-controller="Account">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>

                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>