src/WebUI/Controllers/JoinServerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zenbot.Domain.Shared.Entities.Bot.Dtos;
using Zenbot.Domain.Shared.Interfaces;
using Zenbot.WebUI.Extensions;

namespace Zenbot.WebUI.Controllers
{
    [Authorize]
    public class JoinServerController : Controller
    {
        private readonly IBotUserGuildService _botUserGuildService;
        private readonly IWelcomeMessageService _welcomeMessageService;
        private readonly INotyfService _notyf;

        public JoinServerController(IBotUserGuildService botUserGuildService, IWelcomeMessageService welcomeMessageService, INotyfService notyf)
        {
            _botUserGuildService = botUserGuildService;
            _welcomeMessageService = welcomeMessageService;
            _notyf = notyf;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userid = HttpContext.GetOperatorUserId();
            var guilds = await _botUserGuildService.GetAllGuildsByUserId((ulong)userid);
            return View(guilds);
        }


        public async Task<IActionResult> Edit(int guildId, string guildName)
        {
            var message = await _welcomeMessageService.GetWelcomeMessagesByGuildId(guildId);

            ViewBag.guildId = guildId;
            ViewBag.guildName = guildName;

            if (message != null)
            {
                var messageDto = new WelcomeMessageDto
                {
                    Message = message.Message,
                    IsActive = message.IsActive,
                    GuildId = message.GuildId,
                    Id = message.Id
                };
                return View(messageDto);
            }
            ViewBag.info = "The placeholder is the default Message for Welcomeing the new user, but you can always customize it.";
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(WelcomeMessageDto dto)
        {
            var bMessage = await _welcomeMessageService.UpdateWelcomeMessage(dto);
            if (bMessage) {
                _notyf.Success("Welcome message updated successfully");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                _notyf.Error("Error occured during updating Welcome message"); return View(dto);
            }
        }
    }
}

src/WebUI/Views/JoinServer/Edit.cshtml
@using Zenbot.Domain.Shared.Entities.Bot.Dtos
@model WelcomeMessageDto

@{
    ViewData["Title"] = "Welcome";
    Layout = "_PanelLayout";
}

<div class="row g-3 my-2 bg-white pb-3">
    <div class="d-flex justify-content-between px-3">
        <div class="col-md-3">
        </div>



        <div class="col-md-4">
                <div class=" custom-lightGray-bg shadow-sm d-flex justify-content-around align-items-center rounded py-2">
                    <div class="d-flex justify-content-around align-items-center">
                        <p class="fs-5 mb-0">Welcome Message Settings</p>
                        <i class="fas fa-birthday-cake fs-5 p-2"></i>
                    </div>
                </div>
        </div>
    </div>

    <div class="p-4">
        <h5>Update Welcome Message For <strong><i>@ViewBag.guildName</i></strong> Server</h5>
        <div class="p-4 border border-1 rounded-2">
            <form asp-action="Edit" method="post">

                <input asp-for="@Model.Id" class="form-control" hidden />
                <input asp-for="@Model.GuildId" class="form-control" value="@ViewBag.guildId" hidden/>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">
                        <p class="fs-6 text-secondary">@ViewBag.info</p>
                        <p><strong>Note: </strong>Please use `{username}` where ever you want to be your user's name.</p>
                    </label>
                    <textarea asp-for="@Model.Message" class="form-control" id="exampleFormControlTextarea1" rows="4"
                              placeholder="Welcome dear {username} \n Now we're much stronger by having you in our team!\n **Thank you for joining us**">
                    </textarea>
                </div>
                <div class="form-check form-switch d-flex justify-content-between">
                    <div>
                        <input class="form-check-input " type="checkbox" id="flexSwitchCheckChecked" asp-for="@Model.IsActive">
                        <label class="form-check-label" for="flexSwitchCheckChecked">Enable/Disable</label>
                    </div>
                    <div>
                        <input type="submit" value="Save" class="btn btn-dark" />
                    </div>
                </div>
                <div class=" note">If you <strong>Disable</strong> this feature, Zenbot won't use it for your server.</div>
            </form>
        </div>

    </div>

</div>

src/WebUI/Views/JoinServer/Index.cshtml
@using Zenbot.Domain.Shared.Entities.Bot
@model IEnumerable<BotUserGuild>

@{
    ViewData["Title"] = "Welcome";
    Layout = "_PanelLayout";
    var counter = 1;
}

<div class="row g-3 my-2 bg-white pb-3">
    <div class="d-flex justify-content-between px-3">
        <div class="col-md-3">
            

        </div>

       

        <div class="col-md-3">
            <a href="#" class="text-dark">
                <div class=" custom-lightGray-bg shadow-sm d-flex justify-content-around align-items-center rounded py-2">
                    <div class="d-flex justify-content-around align-items-center">
                        <p class="fs-5 mb-0">Join Server Settings</p>
                        <i class="fas fa-birthday-cake fs-5 p-2"></i>
                    </div>
                </div>
            </a>

        </div>
    </div>

    <div class="p-4">
        <h5>All Servers</h5>
        <div class="p-4 border border-1 rounded-2">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Server Name</th>
                        <th scope="col">Join Date</th>
                        <th scope="col">Welcome Message Settings</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">
                            <th scope="row">@counter</th>
                            <td>@item.Guild.GuildName</td>
                            <td>@item.Guild.JoinDate.ToString("MMM dd yyyy")</td>
                            <td><a asp-action="Edit" asp-controller="JoinServer" asp-route-guildId="@item.GuildId"asp-route-guildName="@item.Guild.GuildName"><i class="fas fa-cogs me-2"></i></a></td>
                        </tr>
                        counter++;
                    }

                  
                </tbody>
            </table>
        </div>

    </div>

</div>


  